### ISSUE TITLE
Телефон в описі водойми має бути клікабельним

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_ios#11]
Користувачу має бути зручно користуватись нашим додатком.
Натиснув на номер телефону - і відразу домовився за рибалку.

**Comment by stal1n274** [comment]
Воно нікуди не дзвонить :)

Потрібно додати "+" в момент набору номера.
Щоб було не так:
380978828222
А ось так:
+380978828222

**Comment by akyryl** [comment]
Fixed
