### ISSUE TITLE
Додати в опис водойми час останнього оновлення інформації

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_ios#12]
Нашим користувачів турбує те, чи дійсно є актуальна інформація на сайті. Не хотілось би поїхати на рибалку за лящом, коли там клює лише червонопірка. Або взяв з собою 50 гривень на рибалку, а насправді з 2013 року там плата вже 75 і доводиться десь позичати і т.д. і т.п.

Користувач задоволений, коли бачить, що інформація про водойму оновлена востаннє в цьому ж році, чи навіть в цьому ж місяці.

Ця дата для кожної водойми знаходиться тут: 
`http://api.rivnefish.com/markers/97/`
  _"modify_date": "2015-09-10T19:10:37"_

**Comment by akyryl** [comment]
Fixed
