### ISSUE TITLE
Додати інформацію про умови відпочинку

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_ios#15]
Інформація про особливості та умови відпочинку на водоймі ніде не виводиться. Це потрібно виправити. Пропоную виводити це в детальній інформації про водойму.

Ці дані повертає метод http://api.rivnefish.com/markers/
Поле називається _Conveniences_

![image](https://cloud.githubusercontent.com/assets/5851581/16547427/19cc26cc-4176-11e6-9e8c-ec5a61200ce8.png)

**Comment by akyryl** [comment]
fixed
