### ISSUE TITLE
У карти відсутній режим "Супутник"

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_ios#16]
Ми маємо лише топографічний режим перегляду мапи з рибними місцями.
Зорієтуватись на місцевості без фотографій з супутника вкрай тяжко.

Також в режимі перегляду землі легшу обрати місце для рибалки і навіть вибрати ділянки з перспективними глибинами(як наслідок з кращими шансами знайти рибу).

**Comment by akyryl** [comment]
Fixed in release 1.3.0
