### ISSUE TITLE
Виводити кружечки для зображень водойми

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_ios#9]
Користувач може й не підозрювати, що до водойми завантажено кілька фотографій.
Потрібно реалізувати ось такі ось ідентифікатори, як це зроблено в додатку для андройду:
![image](https://cloud.githubusercontent.com/assets/5851581/12016669/7c1c96b8-ad56-11e5-86e3-719ff4c1aa2a.png)

**Comment by akyryl** [comment]
Fixed. If there are too many dots, only 10 are displayed.
